GENRES = [
    ('Alternative', 'Alternative'),
    ('Anime', 'Anime'),
    ('Blues', 'Blues'),
    ('Childrens Music', 'Childrens Music'),
    ('Classical', 'Classical'),
    ('Comedy', 'Comedy'),
    ('Commercial', 'Commercial'),
    ('Country', 'Country'),
    ('Dance', 'Dance'),
    ('Electronic', 'Electronic'),
    ('Pop', 'Pop'),
    ('Indie', 'Indie'),
    ('Bluegrass', 'Bluegrass'),
    ('Gospel', 'Gospel'),
    ('Hip-Hop', 'Hip-Hop'),
    ('Rap', 'Rap'),
    ('Instrumental', 'Instrumental'),
    ('Jazz', 'Jazz'),
    ('Latin', 'Latin'),
    ('New Age', 'New Age'),
    ('R&B/Soul', 'R&B/Soul'),
    ('Reggae', 'Reggae'),
    ('Rock', 'Rock'),
    ('Singer', 'Singer'),
    ('Songwriter', 'Songwriter'),
    ('Vocal', 'Vocal'),
    ('World', 'World'),
    ('Metal', 'Metal'),
    ('Other', 'Other')
]

DAYS = [
    ('Mon', 'Monday'),
    ('Tues', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thurs', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
    ('Sun', 'Sunday'),
]

TIMES = [
    ('01:00', '1 am'), ('01:30', '1:30 am'),
    ('02:00', '2 am'), ('02:30', '2:30 am'),
    ('03:00', '3 am'), ('03:30', '3:30 am'),
    ('04:00', '4 am'), ('04:30', '4:30 am'),
    ('05:00', '5 am'), ('05:30', '5:30 am'),
    ('06:00', '6 am'), ('06:30', '6:30 am'),
    ('07:00', '7 am'), ('07:30', '7:30 am'),
    ('08:00', '8 am'), ('08:30', '8:30 am'),
    ('09:00', '9 am'), ('09:30', '9:30 am'),
    ('10:00', '10 am'), ('10:30', '10:30 am'),
    ('11:00', '11 am'), ('11:30', '11:30 am'),
    ('12:00', '12 pm'), ('12:30', '12:30 pm'),
    ('13:00', '1 pm'), ('13:30', '1:30 pm'),
    ('14:00', '2 pm'), ('14:30', '2:30 pm'),
    ('15:00', '3 pm'), ('15:30', '3:30 pm'),
    ('16:00', '4 pm'), ('16:30', '4:30 pm'),
    ('17:00', '5 pm'), ('17:30', '5:30 pm'),
    ('18:00', '6 pm'), ('18:30', '6:30 pm'),
    ('19:00', '7 pm'), ('19:30', '7:30 pm'),
    ('20:00', '8 pm'), ('20:30', '8:30 pm'),
    ('21:00', '9 pm'), ('21:30', '9:30 pm'),
    ('22:00', '10 pm'), ('22:30', '10:30 pm'),
    ('23:00', '11 pm'), ('23:30', '11:30 pm'),
    ('24:00', '12 am'), ('24:30', '12:30 am'),
]

INSTRUMENT_CLASSES = [
    ('Percussion', 'Percussion'),
    ('Strings', 'Strings'),
    ('KPO', 'Keyboard, Piano, or Organ'),
    ('Woodwind', 'Woodwind'),
    ('Brass', 'Brass'),
    ('Electronic', 'Electronic'),
    ('CG', 'Computer Generated'),
    ('Vocal', 'Vocal'),
    ('UCMI', 'Unconventional Musical Instrument'),
    ('Other', 'Other'),

]

STATES = [
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('DC', 'District of Columbia'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming')
          ]