GENRES = [
    ('Alternative', 'Alternative'),
    ('Anime', 'Anime'),
    ('Blues', 'Blues'),
    ('Childrens Music', 'Childrens Music'),
    ('Classical', 'Classical'),
    ('Comedy', 'Comedy'),
    ('Commercial', 'Commercial'),
    ('Country', 'Country'),
    ('Dance', 'Dance'),
    ('Electronic', 'Electronic'),
    ('Pop', 'Pop'),
    ('Indie', 'Indie'),
    ('Bluegrass', 'Bluegrass'),
    ('Gospel', 'Gospel'),
    ('Hip-Hop', 'Hip-Hop'),
    ('Rap', 'Rap'),
    ('Instrumental', 'Instrumental'),
    ('Jazz', 'Jazz'),
    ('Latin', 'Latin'),
    ('New Age', 'New Age'),
    ('R&B/Soul', 'R&B/Soul'),
    ('Reggae', 'Reggae'),
    ('Rock', 'Rock'),
    ('Singer', 'Singer'),
    ('Songwriter', 'Songwriter'),
    ('Vocal', 'Vocal'),
    ('World', 'World'),
    ('Metal', 'Metal'),
    ('Other', 'Other')
]

DAYS = [
    ('Mon', 'Monday'),
    ('Tues', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thurs', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
    ('Sun', 'Sunday'),
]

TIMES = [
    ('1 am', '1 am'), ('1:30 am', '1:30 am'),
    ('2 am', '2 am'), ('2:30 am', '2:30 am'),
    ('3 am', '3 am'), ('3:30 am', '3:30 am'),
    ('4 am', '4 am'), ('4:30 am', '4:30 am'),
    ('5 am', '5 am'), ('5:30 am', '5:30 am'),
    ('6 am', '6 am'), ('6:30 am', '6:30 am'),
    ('7 am', '7 am'), ('7:30 am', '7:30 am'),
    ('8 am', '8 am'), ('8:30 am', '8:30 am'),
    ('9 am', '9 am'), ('9:30 am', '9:30 am'),
    ('10 am', '10 am'), ('10:30 am', '10:30 am'),
    ('11 am', '11 am'), ('11:30 am', '11:30 am'),
    ('12 pm', '12 pm'), ('12:30 pm', '12:30 pm'),
    ('1 pm', '1 pm'), ('1:30 pm', '1:30 pm'),
    ('2 pm', '2 pm'), ('2:30 pm', '2:30 pm'),
    ('3 pm', '3 pm'), ('3:30 pm', '3:30 pm'),
    ('4 pm', '4 pm'), ('4:30 pm', '4:30 pm'),
    ('5 pm', '5 pm'), ('5:30 pm', '5:30 pm'),
    ('6 pm', '6 pm'), ('6:30 pm', '6:30 pm'),
    ('7 pm', '7 pm'), ('7:30 pm', '7:30 pm'),
    ('8 pm', '8 pm'), ('8:30 pm', '8:30 pm'),
    ('9 pm', '9 pm'), ('9:30 pm', '9:30 pm'),
    ('10 pm', '10 pm'), ('10:30 pm', '10:30 pm'),
    ('11 pm', '11 pm'), ('11:30 pm', '11:30 pm'),
    ('12 pm', '12 am'), ('12:30 am', '12:30 am'),
]

INSTRUMENT_CLASSES = [
    ('Percussion', 'Percussion'),
    ('Guitar', 'Guitar'),
    ('Bass', 'Bass'),
    ('Banjo', 'Banjo'),
    ('Upright Bass', 'Upright Bass'),
    ('Violin', 'Violin'),
    ('Chello', 'Chello'),
    ('Strings', 'Strings'),
    ('Lute', 'Lute'),
    ('KPO', 'Keyboard, Piano, or Organ'),
    ('Woodwind', 'Woodwind'),
    ('Brass', 'Brass'),
    ('Electronic', 'Electronic'),
    ('CG', 'Computer Generated'),
    ('Vocal', 'Vocal'),
    ('UCMI', 'Unconventional Musical Instrument'),
    ('Other', 'Other'),

]

STATES = [
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('DC', 'District of Columbia'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming')
          ]