from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.http import Http404
from .views import musician_registration, non_musician_registration, choose, musician_profile, \
    non_musician_profile, update_musician_profile, musician_add_time_frame, musician_update_time_frame, add_genre,\
    update_genres, add_instrument, update_instruments, musician_add_location, update_musician_location, \
    youtube_url_decoder_view, update_video, update_friends, add_profile_image, add_profile_image_non_musician, \
    update_non_musician_profile, update_watched_musicians, LocationCreateView

urlpatterns = [
    url(r'^register-musician/$',
        musician_registration,
        name='register_musician'),
    url(r'^register-non-musician/$',
        non_musician_registration,
        name='register_non_musician'),
    url(r'^login/',
        login,
        name='Login'),
    url(r'^logout/',
        logout, {'next_page': 'main:home'},
        name='Logout'),
    url(r'^choose/$',
        choose, name='choose'),
    url(r'^musician/(?P<user_id>\d+)/$',
        musician_profile,
        name='musician_profile'),
    url(r'^non-musician/(?P<user_id>\d+)/$',
        non_musician_profile,
        name='non_musician_profile'),
    url(r'^musician/update/$',
        update_musician_profile,
        name='musician_update'),
    url(r'^add-availability/',
        musician_add_time_frame,
        name='add_availability'),
    url(r'^update-availability/',
        musician_update_time_frame,
        name='update_availability'),
    url(r'^add-genre/',
        add_genre,
        name='add_genre'),
    url(r'^update-genre/',
        update_genres,
        name='update_genres'),
    url(r'^add-family/',
        add_instrument,
        name='add_instrument'),
    url(r'^update-family/',
        update_instruments,
        name='update_instruments'),
    url(r'^musisian-add-location/',
        LocationCreateView.as_view(),
        name='add_musician_location'),
    url(r'^musician-update-location/',
        update_musician_location,
        name='update_musician_location'),
    url(r'^add-video/',
        youtube_url_decoder_view,
        name='add_youtube_url'),
    url(r'^update-video/',
        update_video,
        name='update_video'),
    url(r'^update-friends/',
        update_friends,
        name='update_friends'),
    url(r'^musician-profile-image/',
        add_profile_image,
        name='musician_profile_image'),
    url(r'^non-musician-profile-image/',
        add_profile_image_non_musician,
        name='non_musician_profile_image'),
    url(r'^non-musician/update/$',
        update_non_musician_profile,
        name='non_musician_update'),
    url(r'^update-watched-musicians/',
        update_watched_musicians,
        name='update_watched_musicians'),
    url(r'^musician-public-profile/(?P<pk>\d+)/',
        Http404,
        name='public_profile'),




]
